hospital:
  name: MERX
  address: 5/F Orient Square Bldg Ortigas Center Pasig City
  hotline: 1234567
  er-hotline: 7654321
  website: exist.com.ph
  logo: https://github.com/erx-medcurial/config-server/blob/master/logo.png?raw=true
  
billing:
  senior-discount-rate: 20%
  pwd-discount-rate: 20%

clinical:
  document-locking:
    discharge-summary: 5

